### ISSUE TITLE
Aclarar en el "for" cuando se ejecuta "post"

### ISSUE THREAD

**Issue by cccaballero** [yorodm/golang-workshop#2]
En day-01/06-control-statments, sobre el `post` ciclo `for` dice: "El post se ejecuta después del ciclo.". Da la impresión de que se refiere a que `post` se ejecuta al terminar todas las iteraciones del ciclo, quizá sea conveniente dejarlo mas claro, algo como: "El post se ejecuta después de cada iteración del ciclo"

**Comment by yorodm** [comment]
Gracias!!. Arreglado
